# from .prompts import BLS_PROMPT, LEVELS_FYI_PROMPT, SYSTEM_MINIMAL
from .prompts_new import BLS_PROMPT, LEVELS_FYI_PROMPT, SYSTEM_MINIMAL
from .llm_configs import DEFAULT_SAMPLING_CONFIG, HPC_CONFIG, HOME_CONFIG, HOME_4GPU_CONFIG
#    - role: Occupation/title
__all__ = [
    "SYSTEM_MINIMAL",
    "BLS_PROMPT",
    "LEVELS_FYI_PROMPT",
    "HOME_CONFIG",
    "HPC_CONFIG",
    "HOME_4GPU_CONFIG",
    "DEFAULT_SAMPLING_CONFIG",
]